name: weather_app
description: "bd calling assignment three"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  change_app_package_name: ^1.4.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: ^3.4.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
